export enum FieldDisponible {
  COMPUTER_SCIENCE = 'COMPUTER_SCIENCE',
  BUSINESS_ADMINISTRATION = 'BUSINESS_ADMINISTRATION',
  DATA_SCIENCE = 'DATA_SCIENCE',
  NETWORKS = 'NETWORKS',
  ELECTRONICS = 'ELECTRONICS',
  MANAGEMENT = 'MANAGEMENT'
}
