export enum FileStatus {
  PENDING_PAYMENT_CHOICE = 'PENDING_PAYMENT_CHOICE',
  PENDING_UPLOAD = 'PENDING_UPLOAD',
  UNDER_REVIEW = 'UNDER_REVIEW',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED'
}