export enum OptionEsprit {
  GENIE_LOGICIEL = 'GENIE_LOGICIEL',
  SECURITE_INFORMATIQUE = 'SECURITE_INFORMATIQUE',
  IA = 'IA',
  BI = 'BI',
  TELECOM = 'TELECOM',
  BUSINESS_ANALYSIS = 'BUSINESS_ANALYSIS',
  FINANCE = 'FINANCE',
  MARKETING = 'MARKETING'
}
